language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: GgS3PFti7WJ40iwus5mbbVjxOxNr+pNLSkkBOJPxsACy2/bWH3V0usJ/pknu7fPOhJpfRTUXUyKaON6KT1vHa3FJIOe2XbJnSaIQDA5Yuf3mUzTNMjiD1CEcf1M+q7B+Eh8M60gVngJ1p9uAVXKv2qiBZFBDytBs8jR2pJydnrR5X8FDn64cdSjos9RaHBKuX/MlF3aj/M6KoiijivDvxadl1RrhbHkzosgN7tUPB+dinw2SRtKDnPDxJltvSGi/HEORt/j2E95bDAR4Cib0J02M4WWd2cBP+VaUrDNoP/zPZ3e7bsNaWHxhcyydMbf2O9XCe5PwffNv0j89/dhgLdqTUvURB/gb8iBR6ZmctDFTZZ43ySVg5B/koRkl9z8dSne7t9S21kyuoshqQLUqKvwTPRKprbsWpiOLt2BhMvZBPMWlMn4aQgSICvkWxLfj/ixtF8OecNx6ONgeSqFZaE8bJlajMr2E6o/Ymoe2kAYYM/cqLgohlkn/P2Ij590aHAVBWSHKWgRs/AJzV3vBy/bu+zLZ4wnQf1viCPl0KBlqulp+4arAEA60803PlT4oOWfLpQ4arX1cUX96eGqlOQ7BqbGRondrt3ItbyR7jYulUwAuSXNF5Ubhui9eoU4NrA0/SU85Q908vQrM9RGc7Jw91CFipM5mQujvOOXRhiI=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
