language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: al8+Yw6PscUhuiegDqltwYxWlIcEIB1L9vzMroLg6NTDHcp5sPRO7RI0LZOYqTNxCLbxCN5ONuVLoYbCYkoCYkO9LzFkmjDDh1CgcklUNy4HkKnAIDVLPO6rKw2+RAtZNuEh81/t7wYKJQjUXlsycwQQtrbkGGnuqKZA3c5Up8bIZIEjknP4zmA+M7F2WuLetW5Od9DUNmQiHZmDK9k1gF+TYH8UTjl2mfFaF0c0XJg+8Pdsc47TY53r0A2y3Vnm4lZUqfOnh5IEOdO12/HMz8wucRP0CKrXhy8OYRx9rTn63JO/1UYOJZ2RkaN5870DZsnJi5f8zWmWCghWogfodxHSysktwY/FjNWtNxoBF4mSPppCC9UejbH//6AzI7XUgT/4yKtrlWNO32H9M0/wTdiRVPdzZCNbk8lwduqeaCPc5+C47nWWlLT4A8u9wQn98zAh/3aZXio8cZkH3J+5DENZioKKjqH+KEqT8p3kMIQDiPVZhbDYZcmKZqO0pl+eyvt/n/dQC5Lxp2UxkTUnEvbYFjSh8bzlft9L59YgJ7B2n5v7V33UfwLqMx359TRaWmgb3nIvki88Z5KUvNkH9LBaNthGxvK7+gxxccRH4BUCeHX0B6mFrMrAxaSucG2tY36MeVKZh7P3y4Mk1cH6NFnACXAzCSCYbBzTBTV/IM4=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
