language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: ApMbqG2VRTcIvJ/tk3hhgmPJMY17ycPate8uNWRgkCepyEDqe0NsySO4I8RVuQgXVLENB8fwMk4ovJz7IaRC0n5PldjNOrkGSbY6Vwvuqw5DUmJfq1jnAIULnhzEgEQYwpDf4ZPQ0nuURo/c3uxqrQ1cRwT1CB7AauF1JSeHyRrOGHSlMtJWyYReoI1ROQzHUNTgO/Mvdxf6d665rc4xEnCjc1CXF9Qwzmz9YqTvOHSMs6il8JP65j/Mfw1+OLbpVMjmwxwIzadarydn4WXazwxiPVLeRGL0M/6HfuARcwJI8eRooUYaE3JiUzXJIwz9PJtQ6exwhS21u536zCxHMvJmJlhMlhBDlgomMleFCsgWvPHvMxuBo5QEpFper75BuRdZspHspAgWrOTExISxE2Qx2DrDHuRPZkOJG6Fo7O5gCQ8Gy0jx6en4P5UnXAzm1Xq9WLV9cWRsvktnyz/Jpv8iZGuP+8fNiWvWYUc1xj4u6Q+9iM/SeeiHtXgmqAk9zqtCv8Ceg2WscW9q3mKlL40b32FxvTlMBE5akpd1Z6Qgx9kw/uxczt5qXzBt0iT4JvSh8xvBws91R/0STJFJ7/Ex44iQJvYFVJngL3T8dh1OjiqQLxEeyhAr7bUnMiTZD+RavJ18krmQquxeagO9ukVdwyAWpTbMg89Tn5GLY/U=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
